# Generated by Django 2.2.1 on 2019-06-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_comments', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
    ]
